<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 sum = 1;</code>
     */
    private $sum = 0;

    public function __construct() {
        \GPBMetadata\Calculator::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 sum = 1;</code>
     * @return int
     */
    public function getSum()
    {
        return $this->sum;
    }

    /**
     * Generated from protobuf field <code>int32 sum = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSum($var)
    {
        GPBUtil::checkInt32($var);
        $this->sum = $var;

        return $this;
    }

}

