<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace GPBMetadata;

class Calculator
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a90010a1063616c63756c61746f722e70726f746f120463616c63221f0a" .
            "075265717565737412090a016118012001280512090a0162180220012805" .
            "22170a08526573706f6e7365120b0a0373756d18012001280532340a0a43" .
            "616c74756c61746f7212260a03416464120d2e63616c632e526571756573" .
            "741a0e2e63616c632e526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

